
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrsconfig
spec:
  replicas: 3
  selector:
   matchLabels:
    type: webserver                       # till here we use wrt to replicaset or deployment details 
  template:                               # this templates is used to create pod specifications
   metadata:
    name: mypodconfig
    labels:
     type: webserver
   spec:
     containers:
      - image: nginx
        name: c1
        volumeMounts:
         - name: config-volume              # some name
           mountPath: /etc/config
     volumes:                               # **** This is were you would like your config text files to be stored in the container ***** 
      - name: config-volume                 #  this name should be same on the volume mounts 
        configMap:                          # check >> kubectl get configmap , output should have config1 created using yml file
         name: config1                      # the pre existing config1 on your cluster is selected to be mounted on every pod *******
