---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrsconfig
spec:
  replicas: 3
  selector:
   matchLabels:
    type: webserver
  template:
   metadata:
    name: mypodconfig
    labels:
     type: webserver
  spec:
   containers:
    - image: nginx
      name: c1
      volumeMounts:                            # **** This is were you would like your config text files to be stored in the container ***** #
       - name: config-volume
         mountPath: /etc/config
  volumes:
   - name: config-volume                      #  this name should be same on the volume mounts 
     configMap:
     name: config1                            # the pre existing config1 file on your cluster is selected to be mounted on every pod *******
