apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: tomyreplica
 labels: ver01
   author: parktickets
   tier: frontend
spec:
 replicas: 10
 selector:
   matchLabels:
     tier: frontend
 template:
  metadata:
   labels:
     tier: frontend
  spec:
    containers:
    - name: conti1
      image: tomcat
      ports:
       - containerPort: 8080
         hostPort: 9191
